services:
  deepseek-chat:
    image: deepseek-chat-gpu-russian:t1
    # build: .
    restart: always
    ports:
      - "7860:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_HOST=127.0.0.1:11434
      # - OLLAMA_LLM_LIBRARY=cuda
      # - OLLAMA_CONTEXT_SIZE=2048
      # - OLLAMA_NUM_PARALLEL=8
      # - OLLAMA_NOHISTORY=false
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: ["/entrypoint.sh"]
