services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - OLLAMA_BACKEND=cuda
    volumes:
      - ./models:/root/.ollama/models
    ports:
      - "11434:11434"
    command: >
      /bin/sh -c "
      ollama list | grep -q 'deepseek-r1:1.5b' || ollama pull deepseek-r1:1.5b &&
      ollama list | grep -q 'deepseek-r1:7b' || ollama pull deepseek-r1:7b &&
      OLLAMA_BACKEND=cuda ollama serve
      "

  gradio:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    container_name: gradio_app
    depends_on:
      - ollama
    ports:
      - "7860:7860"
    environment:
      - OLLAMA_API=http://ollama:11434
    volumes:
      - ./app:/app
    restart: unless-stopped
