services:
  deepseek-chat:
    image: deepseek-chat
    # build: .
    restart: always
    ports:
      - "7860:7860"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_LLM_LIBRARY=cpu
    command: ["/entrypoint.sh"]
